apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-arzo
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jhutar-tenant/my-app/devfile-sample-arzo@sha256:61906dc44d080d4b311da5011f110055ea8215cf94c394aef02c520198e4f3c8
        name: my-nodejs
        resources: {}
status: {}
